---
layout: Manolo VM CV
title: Manolo Vasquez's CV
---
# Manolo Vasquez
BS Data Science student.

<div id="webaddress">
<a href="alexander.21.01.2004@gmail.com">alexander.21.01.2004@gmail.com</a>
| <a href="https://www.linkedin.com/in/manolo-vasquez-mendoza/">My LinkedIn page</a>
</div>


## Currently

I am a motivated Data Science student with hands-on experience in Python, SQL, Excel, and Tableau. Skilled in data cleaning, visualization, and basic machine learning techniques. Passionate about uncovering insights from data and communicating findings clearly to drive informed decisions. Eager to apply analytical and problem-solving skills in real-world projects

### Specialized in

-Data cleaning
-Data Analysis
-Data visualization
-Python
-SQL
-Maxchine Learning



## Education

`2025 - Now`
__Brigham Young University - Idaho.__
- Bachelor of Science in Data Science

`2024-2025`
__BYU Pathway Worldwide__
- Cerfiticate in Web and Computer Programming


## Certifications

`2025`
Web and Computer Programming, Brigham Young University - Idaho



## Work Experience



`Teacher / Trainer`
__Missionary Training Center__ sept. 2024 - mar. 2025
Lima, Perú

-Supervised , teach and counsel new young missionaries, improving missionary’s skills by 20% each week using evaluations data with Tableau.

-Using Excel and Tableau, identifying key skill gaps. Developed and delivered targeted instruction to address those gaps, resulting in measurable improvements in individual progress and overall group effectiveness.


`Full-Time Missionary`
__La Iglesia de Jesucristo de los Santos de los Ultimos Dias__  abr. 2022 - may. 2024
Cusco, Cusco, Perú

-Led small and medium-sized groups and delivered training on teaching skills and doctrinal understanding, achieving a 20% improvement in performance

-Conducted research and tracked performance data to identify key trends and improvement opportunities, providing actionable insights for decision-making

-Strengthened communication and leadership skills through collaboration, team coordination, and public presentations, enhancing group engagement and performance.

-Trained more than 30 volunteers in prospecting, networking, communication, and leadership, who went on to become leaders in organization

-Develop efficient communication skills, speaking to over 100 visitors per day

-Used diverse selling methods such as Public Contacting, Social Media and Door knocking which increased the monthly new-membership.


`Product Analyst`
__Importadora MMASH SAC__ abr. 2021 - abr. 2022
Lima, Perú

-Executed in-depth market research and validated supplier information, enhancing sourcing accuracy and supporting data-driven purchasing decisions that improved cost and earning efficiency by 10%

-Optimized Excel-based pricing and product databases and conducted in-depth competitive analysis, driving data-informed decisions that cut costs and production time by 8%.



<!-- ### Footer

Last updated: May 2013 -->